title: John Galeazzi # your name (or website title) here
logo: "/images/My headshot.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Software Engineer with 15+ years of operations and technical leadership.  Possess
  Masters of Business Administration from New York University and BS in Physics from
  Loyola University
  <br><br>
  Currently transitioning from Active Duty military service and working on freelance
  projects for a variety of customers in the US and abroad.
  <br><br>
  <a href="https://www.linkedin.com/in/johngaleazzi/">View My LinkedIn Profile</a> 
  <br><br>
  [My Resume](pdf/j_galeazzi_resume_08_2020_scrubbed.pdf)
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
